/** Auto-generated by tools/build-offline-catalog.mjs — do not edit. */
export function requireLyricsShard(shard: string): Record<string, string> {
  switch (shard) {
    case '00':
      return require('../../assets/catalog/lyrics/00.json') as Record<string, string>;
    case '01':
      return require('../../assets/catalog/lyrics/01.json') as Record<string, string>;
    case '02':
      return require('../../assets/catalog/lyrics/02.json') as Record<string, string>;
    case '03':
      return require('../../assets/catalog/lyrics/03.json') as Record<string, string>;
    case '04':
      return require('../../assets/catalog/lyrics/04.json') as Record<string, string>;
    case '05':
      return require('../../assets/catalog/lyrics/05.json') as Record<string, string>;
    case '06':
      return require('../../assets/catalog/lyrics/06.json') as Record<string, string>;
    case '07':
      return require('../../assets/catalog/lyrics/07.json') as Record<string, string>;
    case '08':
      return require('../../assets/catalog/lyrics/08.json') as Record<string, string>;
    case '09':
      return require('../../assets/catalog/lyrics/09.json') as Record<string, string>;
    case '10':
      return require('../../assets/catalog/lyrics/10.json') as Record<string, string>;
    case '11':
      return require('../../assets/catalog/lyrics/11.json') as Record<string, string>;
    case '12':
      return require('../../assets/catalog/lyrics/12.json') as Record<string, string>;
    case '13':
      return require('../../assets/catalog/lyrics/13.json') as Record<string, string>;
    case '14':
      return require('../../assets/catalog/lyrics/14.json') as Record<string, string>;
    case '15':
      return require('../../assets/catalog/lyrics/15.json') as Record<string, string>;
    default:
      return {};
  }
}
