/** Auto-generated by tools/ingest-musicbrainz-metadata.mjs — do not edit manually */
import type { MetadataBatchPayload } from './types';

export const METADATA_BUNDLED_VERSION = 'mb-5000-v1';
export const METADATA_BUNDLED_TOTAL_HINT = 5000;

export const BUNDLED_METADATA_CHUNKS: MetadataBatchPayload[] = [
  require('../../assets/metadata/chunk-01.json'),
  require('../../assets/metadata/chunk-02.json'),
  require('../../assets/metadata/chunk-03.json')
];
