/** Auto-generated by tools/append-metadata-artists.mjs — do not edit manually */
import type { MetadataBatchPayload } from './types';

export const METADATA_BUNDLED_VERSION = 'mb-5200-v2';
export const METADATA_BUNDLED_TOTAL_HINT = 5200;

let cachedChunks: MetadataBatchPayload[] | null = null;

/** Parses chunk JSON on first use — not when Chords tab loads. */
export function getBundledMetadataChunks(): MetadataBatchPayload[] {
  if (!cachedChunks) {
    cachedChunks = [
      require('../../assets/metadata/chunk-01.json'),
      require('../../assets/metadata/chunk-02.json'),
      require('../../assets/metadata/chunk-03.json'),
    ];
  }
  return cachedChunks;
}
